const {
    toYAML,
    fromYAML
} = require("../index.js")
// Example of the JSON object that was generated by your YAML-to-JSON code
const jsonObject = {
    "name": "My Application",
    "settings": {
        "database": {
            "host": "localhost",
            "port": 3306
        },
        "api_key": "YOUR_API_KEY"
    },
    "another_settings": {
        "database": {
            "host": "localhost",
            "port": 3306
        },
        "api_key": "YOUR_API_KEY"
    },
    "more_settings": {
        "db": {
            "host": "remotehost"
        }
    },
    "copy_of_more_settings": {
        "db": {
            "host": "remotehost"
        }
    }
};

const yamlOutput = toYAML(jsonObject);

console.log(yamlOutput);
